### ISSUE TITLE
VS2012 Solution -> VS2010 Solution

### ISSUE THREAD

**Issue by chessmaster42** [SEModCommunity/SE-Community-Mod-API#1]
Need to convert the solution back to a VS2010 solution file or exclude it from the repo entirely and only include the projects.

**Comment by fvgoulet** [comment]
I understood that you already have VS2010 installed on your computer, please replace the solution by a 2010.sln one or completely remove the .sln from the repo.

**Comment by chessmaster42** [comment]
I have the updated solution file pending. Now that I have repo access I'll get it committed and pushed tonight.

**Comment by chessmaster42** [comment]
Completed in 442c3c49a9cf6014d0983533fb8ad1e509928655
