### ISSUE TITLE
SEServerExtender Will not start server

### ISSUE THREAD

**Issue by Universum01** [SEModCommunity/SE-Community-Mod-API#102]
I have been running with SEServerExtender for awhile now, the server will not start since the last update. Not sure why.

Using SEServerExtender 0.2.8.4 Dev Build but it will not start with any build now.

**Comment by chessmaster42** [comment]
First, do NOT post logs directly into the issues. You need to put it on an external site such as pastebin.com or using the gist feature of github. I have edited your initial issue to remove the log content.

Second, this error is coming from deep inside the game code so I'd bet that either something wasn't updated correctly in your SE install or that your world data might be corrupted. I will look into this further as soon as you post links to full logs for us to look through.

**Comment by Krunch** [comment]
I have the same issue, server does not want to start. There are no logs generating either. So I can't show anything. It just does not start. Using the regular SEServerExtender.exe to load the wrapper manually and then clicking Start Server... does nothing.

**Comment by Universum01** [comment]
Ok i got it working. Rather then just update changes like i always do, i uploaded a clean copy of all files(Took a while) and made sure it wasn't blocked on the firewall.

**Comment by Krunch** [comment]
That is what I always do, but it does not work for me.

**Comment by Krunch** [comment]
Don't mind me, I had a typo in the path.

**Comment by Zaragoss** [comment]
It is now working with the correct path.

Maybe you can insert an option to set up the correct path in the tool to get it working again with a simple shortcut.

I like the tool.

the problem shows up after 2.8.0 the last working shortcut version without any path changes.

**Comment by chessmaster42** [comment]
Please test again with the latest dev build and let us know how it goes. It should detect the install more easily without modifying the shortcut.

**Comment by Zaragoss** [comment]
files copied 
shortcut generated 
and it works.

many thx.
