### ISSUE TITLE
Server will not load Saved Instance or World

### ISSUE THREAD

**Issue by cygnes82517** [SEModCommunity/SE-Community-Mod-API#103]
as already posted, when you click "start Server" in the console all you get is "Finished Loading Network Manager"

that's it.. no error 

strange.

**Comment by AlienXAXS** [comment]
Hi Paul,
Check to see if the space engineers dedicated server cfg has the full path to your save world location in the < LoadWorld > < /LoadWorld > area.

**Comment by cygnes82517** [comment]
Hello there Mark, thanks for that i'll have a look shortly and check it's pointing to the right place.

Cheers

**Comment by cygnes82517** [comment]
the <LoadWorld> peramiter is correct, is it fusy on folder naming? i have a space and "-" in the folder path.. ?

**Comment by AlienXAXS** [comment]
Na should be okay with any win32 based folder names.

Check the server log file, you can find it in %programdata%\spaceengineersdedicated

**Comment by cygnes82517** [comment]
this is all it says "2014-08-11 15:36:16.983 - Thread:   6 ->  Exiting.."

poop :(

**Comment by AlienXAXS** [comment]
Come on ts3 later, i will fix it for you.

**Comment by cygnes82517** [comment]
Cheers Mark.

**Comment by chessmaster42** [comment]
Due to a bug that has been fixed but not released yet you need to set gamepath to the root folder of your SpaceEngineers install. So if you're running SEServerExtender from C:\SpaceEngineers\DedicatedServer64 then you need to set gamepath="C:\SpaceEngineers" in the command line

**Comment by cygnes82517** [comment]
Brilliant ! that worked a treat !

thanks
 now to figure out why the server doesnt show in the server list or on my Local LAN.

**Comment by chessmaster42** [comment]
As the question has been answered I am now closing out this issue.
