### ISSUE TITLE
Running Multiple Instances

### ISSUE THREAD

**Issue by Ragonz2** [SEModCommunity/SE-Community-Mod-API#106]
When running multiple instances of SEServerExtender we see something called WmiPrvSE.exe using a large % of CPU

Issue occurs on
Server 2008R2
Server 2012
Server 2012R2

When 1 instance is open the program shows in task manager but uses 0% cpu
when more than 2 instances are open it starts using CPU but a small amount
more than this it starts hitting the CPU hard.

I have a feeling its linked to autosave.

**Comment by chessmaster42** [comment]
Couple things to try:

A) Restart the “Windows Management Instrumentation” service
B) Download and install http://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=1157 or it's equivalent for Server 2008 and Server 2012
C) Set the nogui and nowcf command line args to see if something .NET related is talking to the management service too often

Let me know if any of that works.

**Comment by chessmaster42** [comment]
Closing as there has been no response in over a week.
