### ISSUE TITLE
[v0.2.9.3-dev] Failed to initialize server

### ISSUE THREAD

**Issue by Universum01** [SEModCommunity/SE-Community-Mod-API#107]
Getting this on starting SE-Extender, Server will not start as well with it.

http://pastebin.com/5VSvYXMp

**Comment by chessmaster42** [comment]
Can you please post links to the API error log and the main API log? The game log is not enough information.

**Comment by chessmaster42** [comment]
Closing as there has been no response with detailed information in 5 days.
