### ISSUE TITLE
2.9.6 Issues

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#109]
My server just shuts down after about 10-20 mins. I reverted back to 2.9.5 and it seems to be fine. 

What are the logs you need and where are they located.  

Thanks,

-New

**Comment by ghost** [comment]
http://pastebin.com/9skbwtCt

**Comment by ghost** [comment]
I did a complete re-install, let's see if this work. I'll report back

**Comment by ghost** [comment]
Shut off right away... What am I doing wrong?

http://pastebin.com/SzSebp8n

**Comment by ghost** [comment]
Ran for a good amount of time then it shut off:

**Comment by ghost** [comment]
Latest Crash:

http://pastebin.com/uXWSgJJ5

**Comment by ghost** [comment]
Disabled all mods, will post if this fixes the issue.

**Comment by chessmaster42** [comment]
This is a known game bug with floating objects as of 1.043 and not a bug with SEServerExtender or the SEModAPI. As such I am closing this issue.
