### ISSUE TITLE
Create derivative of ConfigFile interface for GlobalEvents.sbc

### ISSUE THREAD

**Issue by fvgoulet** [SEModCommunity/SE-Community-Mod-API#11]

**Comment by chessmaster42** [comment]
I'm starting on this one and the corresponding tab in the config tool tonight.

**Comment by chessmaster42** [comment]
Completed in b72b4498a3cff98e2ff7d9d7bbd45763b05e3a30

**Comment by chessmaster42** [comment]
I believe that this interface is now complete

**Comment by chessmaster42** [comment]
Code review complete and interface is complete.
