### ISSUE TITLE
Program Stops Responded After 24 Hours

### ISSUE THREAD

**Issue by Ryahn** [SEModCommunity/SE-Community-Mod-API#110]
After leaving the program running on my dedicated server for 24 hours. The whole program is white and in not responding. The server is still running however but in order to stop the program, I have to hard shutdown the server. I dont like doing this.

**Comment by chessmaster42** [comment]
There is a rogue bug in the GUI that we haven't yet located. There is also an issue already tracking this problem. Please see bug #105 for reference and post any more info you have to that issue.

I am closing this as a duplicate.
