### ISSUE TITLE
Shutting down server... Done

### ISSUE THREAD

**Issue by NTchrist** [SEModCommunity/SE-Community-Mod-API#111]
SEServerExtender:494691 Game:356865

Looking at the logs, this might be related to that item pickup bug, but either way, it doesn't indicate anything other than a normal looking shutdown in the console.  The first 2 times I thought a co-admin was being an asshole.

http://pastie.org/9477165

**Comment by AnonymousMonkey75** [comment]
I'm pretty sure that error there is related to the no pickup bug.

**Comment by chessmaster42** [comment]
Closing as this is related to the floating object pickup bug. The game bug has also been fixed as of today's patch.
