### ISSUE TITLE
nogui option does not load plugins

### ISSUE THREAD

**Issue by AnonymousMonkey75** [SEModCommunity/SE-Community-Mod-API#112]
title says it all really, if I use nogui the motd plugin won't load.

**Comment by chessmaster42** [comment]
Can you please post the full command line that you are using?

**Comment by AnonymousMonkey75** [comment]
"C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\DedicatedServer64\SEServerExtender.exe" gamepath="C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers" instance=se nogui

**Comment by AnonymousMonkey75** [comment]
I have also just tried simply: "C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\DedicatedServer64\SEServerExtender.exe"  instance=se nogui

**Comment by AnonymousMonkey75** [comment]
Also I'm not sure if this related in anyway and might needs its own issue but. With the latest .2.9.9 build and the previous build in order for the /gui command to work in chat I first must run the seservergui, connect, then I can close it and the /gui chat command will work. 

I notice that upon running and connecting with seservergui that three messages come up:

finished loading networkmanager
finished loading playermanager
finished loading playermap

Just FYI, not sure if helpful.

**Comment by chessmaster42** [comment]
What is the full path to the instance you are trying to load? Also, make sure that the instance name is inside of quotes.

**Comment by AnonymousMonkey75** [comment]
I just set up another server on my local machine here with the exact same result :(

The instance is at C:\ProgramData\SpaceEngineersDedicated\SE.

I did not have the instance in "" but now I do so my shortcut looks like this:

"C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\DedicatedServer64\SEServerExtender.exe" gamepath="C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers" instance="se" nogui

However it still does not load the plugins. I can see in the console where it tries but it just never finds any.

Of course it still works just fine with the nogui switch.

EDIT:
Doing testing on another machine:

Also this command does not load plugins for me either:
E:\steamlibrary\SteamApps\common\SpaceEngineers\DedicatedServer64\SEServerExtender.exe gamepath="e:\steamlibrary\steamapps\common\spaceengineers" instance="se" autostart

If I remove the autostart it loads fine. So since nogui implies autostart I bet the problem is with autostart.

At this point I'll do a teamviewer session if you wish so I can show you.

**Comment by chessmaster42** [comment]
Thanks for the details. I have a pretty good idea how it would be related to autostart. Also, you don't need that gamepath arg. It will check the parent folder that it's running it to see if that's a valid game path and in your case this is true. I will post back when I have more details about how this could be happening with autostart.

**Comment by chessmaster42** [comment]
This should now be fixed. Please re-test on the latest build and let us know if your issue is resolved.

**Comment by AnonymousMonkey75** [comment]
It look like it see's the plug-ins correctly now, I can see it find them in the console, however nothing responds to chat commands, even /gui. 

Plugins are also broke but I think that has more to do with the SE update they don't seem to work if I use the nogui switch or not.

**Comment by chessmaster42** [comment]
Fixed as of the latest release build. Plugin loading and chat commands are both fixed and confirmed working. Closing out this issue.
