### ISSUE TITLE
0.2.9.6 - Gui will "stop responding" 

### ISSUE THREAD

**Issue by AnonymousMonkey75** [SEModCommunity/SE-Community-Mod-API#113]
Happens every time I use the gui. I have tried on a pair of servers. Both Server 2012. Clean installs .After a few hours it just says not responding. What logs do you need?

**Comment by chessmaster42** [comment]
This has been reported several times already and is being tracked in issue #105 . Please add any information you have to that issue.

Closing as a duplicate.
