### ISSUE TITLE
[v0.2.9.8-dev] - a crash

### ISSUE THREAD

**Issue by AnonymousMonkey75** [SEModCommunity/SE-Community-Mod-API#114]
If you run .2.9.8 with nogui, then you do the /gui chat command to bring it up and try to import a cubegrid such as a ship it will crash.

**Comment by Hasbinbad** [comment]
1.) load sese
2.) close stock GUI
3.) run/connect remote gui
4.) type /gui in the chat of the remote GUI
5.) close the remote GUI
6.) click entities tab
7.) click an entity
8.) click impoort
expected: import dialogue
actual: stock GUI Not Responding (however, server is still running fine at this point, without the "no connection message," and one is able to transfer items in game).
9.) click the x in the stock GUI to close it
expected: stock GUI shuts down.
actual: closes the console too (shuts down server)

I haven't repeated this, but that is step by step why some issue happened and my observations about it.

Sounds like it's the same issue, so copying my reply to the other thread here.

**Comment by chessmaster42** [comment]
Fixed in ac75214e0eeec4780183686c28a9e099d6469948 and is in the latest dev release, 0.2.9.9. Please download and re-test.

**Comment by AnonymousMonkey75** [comment]
I'm not sure I can re-produce but I did have .2.9.9 crash on me while editing cubegrids. I tried to reproduce but was unable.
