### ISSUE TITLE
after patch 8/22, chat command deletion not working

### ISSUE THREAD

**Issue by Hasbinbad** [SEModCommunity/SE-Community-Mod-API#119]
I sort of wrote it off as "new version blues," but after seeing another comment..

1.) I used "/delete all nobeacon"
2.) the chat replied that X deletions occured
3.) /save
4.) checked list, observed same # of cubegrids
5.) restarted server (was doing offline maintenance at the time anyway)
6.) checked list, observed same # of cubegrids

7.) repeated 1-6

8.) never got those ships deleted. they are still there.

9.) /save definitely just worked.

**Comment by chessmaster42** [comment]
Deleting always breaks with each game patch until the missing method in the BaseEntityNetworkManager is fixed in the next dev build. Given that the dev build is out this issue should now be fixed.

**Comment by chessmaster42** [comment]
All delete related issues have been fixed in the latest release build. Closing this issue.
