### ISSUE TITLE
REQUEST: OnCubeGridAdded

### ISSUE THREAD

**Issue by Tyrsis** [SEModCommunity/SE-Community-Mod-API#122]
Could we add an OnCubeGridAdded event when the cubegrid is completed adding to scene (or at least at the end of InternalAddEntity in SectorObject

**Comment by chessmaster42** [comment]
This has been completed and the event is "OnCubeGridLoaded"

**Comment by chessmaster42** [comment]
Closing as this was completed some versions ago.
