### ISSUE TITLE
New to SEServerExtender - Failed to start server

### ISSUE THREAD

**Issue by derrickmehaffy** [SEModCommunity/SE-Community-Mod-API#130]
Server OS: Windows Server 2008r2 x64
Dedicated Server Location: C:\Users\blah\Desktop\DedicatedServer\DedicatedServer64
Coped Save World Location: C:\ProgramData\SpaceEngineersDedicated\blah\Saves\USE-V0.002
Mods: C:\ProgramData\SpaceEngineersDedicated\blah\Mods

Output from SEServerExtender: (Attached below, sorry couldn't find log file)

Basically its saying Failed to find method 'random letters and numbers'
and
this world can not be loaded. It has been created in newer version of the game.

I created this world on the most up to date patch and just downloaded SEServerExtender today, most up to date version.

**Comment by derrickmehaffy** [comment]
![kyhikj3](https://cloud.githubusercontent.com/assets/8593673/4095204/2a1bc3f8-2fb1-11e4-8726-a42457714fac.png)

**Comment by chessmaster42** [comment]
This is a non-issue. What you are seeing is what happens after every game patch and isn't a bug. If you download the latest dev build then the validation messages will be gone. I am closing this issue.
