### ISSUE TITLE
Players Logging Into Empty World

### ISSUE THREAD

**Issue by mikeloeven** [SEModCommunity/SE-Community-Mod-API#131]
I have been experiencing an intermittent issue where after several hours of continuous operation either another player or myself will attempt to log into the server upon which we will not have a list of med bays to choose from and must select a spawn ship upon doing so we are deposited into a completely empty world with no spawn ship or asteroids. restarting the client will not resolve this issue however restarting the server wrapper will fix the issue. i have not encountered this issue in single player or the vanilla server and the map has been tested thoroughly and shows no signs of corruption

**Comment by DraygoKorvan** [comment]
What happens when you click Refresh in the spawn selection?

**Comment by mikeloeven** [comment]
absolutely nothing but considering the server is hosted from the same computer i am joining with i am sure ping is not a factor

**Comment by chessmaster42** [comment]
Is there any more information on this? At the very least we need logs to diagnose the problem if in fact it is a bug with SEServerExtender. Please provide as much information as you can.

**Comment by mikeloeven** [comment]
i think you can mark this closed as i have been unable to reproduce since the last few updates it may have simply been a rare fluke

**Comment by mikeloeven** [comment]
there was something in todays change log that looked interesting 
- fixed dedicated servers downloading blank/empty .sbms

i am wondering if the corruption may have something to do with these empty mod files causing parsing issues
