### ISSUE TITLE
Plugins not showing?

### ISSUE THREAD

**Issue by dfac5084** [SEModCommunity/SE-Community-Mod-API#132]
SE-motd and SE-Antigrief are not showing up in the plugins tab and are not responding to any chat commands. (Not activated) 

I dont understand why that might be. I've turned instanced server on and off. Ive extracted the server mods inside ProgramData & inside the actual dedicatedserver64 folder. Still nothing. Also, no errors in log. What am I missing?

**Comment by DraygoKorvan** [comment]
If are running a non-instanced version the mods need to be located in %appdata%\spaceengineersdedicated\mods if you are running an instance they need to be in ProgramData\SpaceEngineersDedicated\InstanceName\Mods

**Comment by dfac5084** [comment]
Hey man, please forgive me. they showed up after i logged into the game server. we are good.
