### ISSUE TITLE
BUG: CubeBlockEntity.Owner throws exception when owner is null (instead of setting 0?)

### ISSUE THREAD

**Issue by Tyrsis** [SEModCommunity/SE-Community-Mod-API#135]
http://pastebin.com/wriWXYug

**Comment by chessmaster42** [comment]
Check the latest code on the main repository. This should be fixed now.

**Comment by Tyrsis** [comment]
While the original bug is fixed, there is an issue with this.  Getting this value takes _a lot_ of time (relatively).

EDIT: I'm going to run more tests, as this may not be the source of the pause.

**Comment by Tyrsis** [comment]
Yeah something else is the source of the lag.  This can be closed.
