### ISSUE TITLE
Canot take hand item tools from toolbar(grinder welder)

### ISSUE THREAD

**Issue by PsychotronicCZ** [SEModCommunity/SE-Community-Mod-API#139]
Greeting after today update to SEServerExtender 0.2.10.6 Dev Build Canot take hand item tools from toolbar(grinder welder)

**Comment by PsychotronicCZ** [comment]
Please anybody help ? I have on hosted DS SEEx 0.2.8.5 i want to update it but then canot load any tool from toolbar into hand ,crazy is the same version 0.2.8.5 from web here is not working same .tested too on my DS on pc .Anybody have sam problem or can help solve this THX very much

**Comment by PsychotronicCZ** [comment]
Is posible to be a problem in .net4.x czech localisation ?

**Comment by fvgoulet** [comment]
We will close this ticket as this one is a duplicate the younger ticket #163 (Which contains more informations)
