### ISSUE TITLE
Crash when placing mod block

### ISSUE THREAD

**Issue by SpyderTheSir** [SEModCommunity/SE-Community-Mod-API#147]
I'm not sure if this is linked to SEServerExtender or the modpack. I'm going to run this up in vanilla shortly and re-test. I'll update this when I have more info from that

Issues occurs when trying to place either slanted or straight small vented window from http://steamcommunity.com/sharedfiles/filedetails/?id=305329302

This log is me starting the server specifically to make it crash :-)
Crash log - http://pastebin.com/SX4KqN1B

**Comment by DraygoKorvan** [comment]
Looks like an issue with the mod itself, did you attempt to run the dedicated server without the extender to verify the issue is with the extender.

Also post crashlogs on gist or pastebin and link here instead of pasting it directly into the issue window.

**Comment by SpyderTheSir** [comment]
Forced a mod re-download as I'd read this helps. It's now working just fine.
