### ISSUE TITLE
ExtenderGUI > Control > Server Properties > Global Settings: "Field not found"

### ISSUE THREAD

**Issue by NTchrist** [SEModCommunity/SE-Community-Mod-API#155]
Under "Global Settings" in the property's configurator, many settings report 'Field not found: "Sandbox.Common.ObjectBuilders.MyConfigDedica..."' instead of their expected values.

**Comment by generalwrex** [comment]
This is because there hasn't been an update yet from thursdays patch and todays hotfix :) Please wait patiently :) chessmaster is very busy with his work.

**Comment by NTchrist** [comment]
@generalwrex

No problem, I just wanted to follow proper procedure and make a bug report in the hopes that some might read it and not spam you guys with reports of the same issue.

**Comment by generalwrex** [comment]
Thank you for that :)

SESE Should still work for hosting your server.
Pretty much every update they change the name of the Methods, which causes some features of the extender to stop working.  It's a pain :)

**Comment by generalwrex** [comment]
I fixed most of the issues over on my fork

https://github.com/generalwrex/SE-Community-Mod-API

the latest update changed voxel maps and cockpits. So dont worry about those method errors in the console, they will be fixed soon.

After its checked over, i might create a pull request.  It all works fine for me

**Comment by Moustachauve** [comment]
This particular problem should now be fixed in lastest dev build. 

Generalwrex, have you fixed the cockpit in your fork?

**Comment by generalwrex** [comment]
I converted it from the ship controller over to the cockpit, since they moved it out for remote control

https://github.com/generalwrex/SE-Community-Mod-API/commit/137b134314f4c1049cbb8cb6398fa41b9c12c1cb

but if you already did the fixes then my fork is useless =P

**Comment by Moustachauve** [comment]
That was the only fix I was missing :)

**Comment by generalwrex** [comment]
I think it needs to be recoded into its own file, for cockpits, then create one for the remote control

**Comment by Moustachauve** [comment]
Continue discution on that issue at this place instead https://github.com/SEModCommunity/SE-Community-Mod-API/issues/156
