### ISSUE TITLE
Create derivative of ConfigFile interface for SpawnGroups.sbc

### ISSUE THREAD

**Issue by fvgoulet** [SEModCommunity/SE-Community-Mod-API#17]

**Comment by chessmaster42** [comment]
I'm starting on this one and the corresponding tab in the config tool tonight.

**Comment by chessmaster42** [comment]
Completed in 220adff09ae446162fdaa42007e9756df37636f6

**Comment by chessmaster42** [comment]
Re-opening as I realized that I don't have the interfaces to the sub-objects completed.

**Comment by fvgoulet** [comment]
- Please note your TODOs into tickets as well as in the code and don't close tickets yourself. Put it in pending code review before doing that. A ticket is not finished until all TODOs aren't cleared. Productivity and maintainability depends on everyone following theses rules perfectly.
- You can easily refer your commits into tickets by typing "update #[ticket number]" in the commit message instead of finding the link and creating a new comment.

**Comment by chessmaster42** [comment]
Working on minor overhaul of manager class to be more flexible with sub-items in interfaces like this one. Also working on finalizing this interface.

**Comment by chessmaster42** [comment]
Finished up a few minor bits after @Moustachauve and this is now verified as complete and reviewed. Closing this issue.
