### ISSUE TITLE
[Crash] Unhandled Exception during LoadConfiguration

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#173]
http://pastebin.com/4hXgK1d4

http://forums.keenswh.com/post/show_single_post?pid=1284606046&postcount=755

DedicatedConfigDefinition.Load() can cause an unhandled exception if SpaceEngineers-Dedicated.cfg is corrupt.

**Comment by ghost** [comment]
See https://github.com/Commander-Scott/SE-Community-Mod-API/tree/Issue-%23173-Exploration for current work on this issue.

**Comment by NotYetRated** [comment]
haha 2 things.
1. Sorry about folder path error.
2. Downloaded and applied the above "issue" files, to generate the more detailed error report, and the server started. Reapplied the current "dev" files, same error.... Even with the path correction.

I deleted everything, recopied the base file in to two folders, a test and a base, applied the current public files to base, and the dev files to test, to ensure everything was fresh.

Test starts. Base does not. And it starts without a shortcut modifier.

**Comment by ghost** [comment]
Fixed in Pull Request: https://github.com/SEModCommunity/SE-Community-Mod-API/pull/174
