### ISSUE TITLE
Lastest Dev and Stable builds - Fatal Exception on start after 1.053 Update

### ISSUE THREAD

**Issue by majikmushi** [SEModCommunity/SE-Community-Mod-API#183]
I cannot find any versions that will work with the latest update. I will post error info when I have a chance to take my server back down. Cheers and Keep up the awesome work.

**Comment by generalwrex** [comment]
Latest release can be found at https://github.com/Tyrsis/SE-Community-Mod-API/releases

**Comment by majikmushi** [comment]
thanks dude, user error on my behalf
