### ISSUE TITLE
SpawnGroup Prefab Manager

### ISSUE THREAD

**Issue by chessmaster42** [SEModCommunity/SE-Community-Mod-API#20]
Need to expand the interface and config tool to manage the prefab objects of Spawn Groups

**Comment by Moustachauve** [comment]
No ability to add Prefabs, to modify the file nor the position in the graphical interface.

**Comment by chessmaster42** [comment]
Working on this today along with some other minor improvements to the manager class to better handle sub-items

**Comment by chessmaster42** [comment]
Closing this as sub-item management is now handled through the main API interface for SpawnGroups
