### ISSUE TITLE
Create a general class for definition wrapper to inherite from

### ISSUE THREAD

**Issue by Moustachauve** [SEModCommunity/SE-Community-Mod-API#24]
Every definition wrapper seems to hold some common methods and values. A general class should be create to avoid code repetition across the classes

**Comment by chessmaster42** [comment]
Taking ownership for overhaul

**Comment by fvgoulet** [comment]
@chessmaster42 I'm assigning the code review to you since you will do ticket #4

**Comment by chessmaster42** [comment]
Taking ownership as I am doing some more minor overhaul to better support all objects

**Comment by chessmaster42** [comment]
Marking as completed and closing now that all main base classes are complete
