### ISSUE TITLE
Change Name property of wrappers to use definition.TypeId

### ISSUE THREAD

**Issue by Moustachauve** [SEModCommunity/SE-Community-Mod-API#25]
The wrappers do not use the same way to get the name of a definition. It should be unified by using definition.TypeId.

**Comment by chessmaster42** [comment]
The overhaul has changed this but I do agree that we need a common method to get the name of the item.

**Comment by chessmaster42** [comment]
Name property is now implementation-specific so I don't think that this issue applies any longer. Implementing classes of the OverLayerDefiniton or it's interfaces can override the Name property and also implement the GetNameFrom method.

**Comment by fvgoulet** [comment]
To give more informations on this ticket, TypeId is implementation specific, meaning that we create id's only to manage contained items list but the TypeId you mention is inside the definition itself. Some sub-classes of MyObjectBuilder_Definitions do not contain Id, meaning that this type shouldn't be managed into the Common interface OverLayerDefinition. On a different point of view, Name is comething common to every of MyObjectBuilder_Definitions sub-classes and is Implementation specific. Name is now defined in implementation and should be re-evaluated before the end of this milestone.
