### ISSUE TITLE
Create a vector3 interface

### ISSUE THREAD

**Issue by Moustachauve** [SEModCommunity/SE-Community-Mod-API#28]
A vector3 struct to handle position and distances should be implemented.

I feel like the API user should not have to handle or even include the game's dll inside his project, so a custom vector struct should be made

**Comment by chessmaster42** [comment]
I think that modders that use the API should be using as much of the game's data types as they can. Yes we want to abstract most of the main content classes but basic things like the VRageMath classes I think could be left as-is. We only want to abstract the SE content not the VRage engine content.

**Comment by fvgoulet** [comment]
Agreed on that point, invalidating the ticket.

We could do a wrapper for vrage math if we find it simplifiable.
