### ISSUE TITLE
Unify comment language

### ISSUE THREAD

**Issue by chessmaster42** [SEModCommunity/SE-Community-Mod-API#3]
Code comments should either be in English or include several localized languages. Using something like google translate to read each comment is not practical for development.

EDIT: Comments seem to be in English for the most part. Only a few places are they in French. Thoughts on moving all to English then?

**Comment by fvgoulet** [comment]
It's a mistake due to automated code generation on some classes. I'll fix it tomorrow around 8-9 PM (-5)

**Comment by fvgoulet** [comment]
In pending code review

**Comment by chessmaster42** [comment]
Last ones are completed in eb2878715d29f8852972002b3c6c17c96ff567af
