### ISSUE TITLE
Unify UI

### ISSUE THREAD

**Issue by Moustachauve** [SEModCommunity/SE-Community-Mod-API#31]
UI elements need to be consistent and have a consistent naming standard

**Comment by chessmaster42** [comment]
Tab controls, tab pages, and labels still need to be converted.

**Comment by Moustachauve** [comment]
I'm going to go through those controls

**Comment by Moustachauve** [comment]
I think everything is nammed correctly and the UI behavior is uniform now

**Comment by chessmaster42** [comment]
Reviewed UI and all appears to be correct now. Marking this as completed and closing.
