### ISSUE TITLE
Create a common interface for configuration files

### ISSUE THREAD

**Issue by fvgoulet** [SEModCommunity/SE-Community-Mod-API#4]
Every configuration file in Content\Data as .sbc file should be serializable/deserializable and have a common interface to work with.

This ticket is intended to create a common interface from which user will derivate from to specialize every configuration file.
- The interface should manage serialization, deserialization and access to items.
- Derivatives should manage attributes access and possible enhancements

**Comment by chessmaster42** [comment]
Taking ownership for wrapper overhaul

**Comment by chessmaster42** [comment]
Relinquishing ownership as overhaul is complete

**Comment by fvgoulet** [comment]
I'm doing your code review

**Comment by fvgoulet** [comment]
@chessmaster42 I'm assigning the code review of the OverLayerDefinition and OverLayerDefinitionManager classes to you

**Comment by chessmaster42** [comment]
I think that the original intent of this issue has since been completed and all that remains are a few of the individual config interfaces.

**Comment by chessmaster42** [comment]
Closing as the OverlayDefinition, OverLayerDefinitionManager, and SerializableDefinitionManager are >90% complete and contain all functions originally needed by this issue.
