### ISSUE TITLE
Unhandeled exception server extender 0.1.8.0

### ISSUE THREAD

**Issue by DraygoKorvan** [SEModCommunity/SE-Community-Mod-API#42]
I think this is caused by a character entity you have selected getting into a cockpit. The character entity disappears from the tree view, but on the right in the properties window it still has the fields where its attempting to pull the data?

---

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntityManagerWrapper.GetAPIEntityList[T,TO](MyObjectBuilderTypeEnum type)
   at SEModAPIInternal.API.Entity.BaseEntityManagerWrapper.GetCharacters()
   at SEServerExtender.SEServerExtender.TreeViewRefresh(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1022 (RTMGDR.030319-1000)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

SEServerExtender
    Assembly Version: 0.1.8.0
    Win32 Version: 0.1.8.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEServerExtender.exe

SEModAPI
    Assembly Version: 0.2.4.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.DLL

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1002 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1001 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1001 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

SEModAPIInternal
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPIInternal.DLL

Sandbox.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

Sandbox.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

Sandbox.Common.XmlSerializers
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

Sandbox.Common.XmlSerializers
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

VRage.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

VRage.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

VRage.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

VRage.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

VRage.Math
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

VRage.Math
    Assembly Version: 1.0.0.0
    Win32 Version: 0.2.4.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SEModAPI.dll

VRage.Math
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/VRage.Math.DLL

Sandbox.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/Sandbox.Common.DLL

VRage.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/VRage.Library.DLL

SpaceEngineersDedicated
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SpaceEngineersDedicated.EXE

Sandbox.Game
    Assembly Version: 0.1.5291.26345
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/Sandbox.Game.DLL

SharpDX
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SharpDX.DLL

HavokWrapper
    Assembly Version: 1.0.5291.26338
    Win32 Version: 
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/HavokWrapper.DLL

VRage.Render
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/VRage.Render.DLL

VRage.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/VRage.Common.DLL

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1015 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1015 (RTMGDR.030319-1000)
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

Sandbox.Common.XmlSerializers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/Sandbox.Common.XmlSerializers.DLL

SteamSDK
    Assembly Version: 0.0.0.0
    Win32 Version: 
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SteamSDK.DLL

Sandbox.Graphics
    Assembly Version: 0.1.5291.26345
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/Sandbox.Graphics.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Sandbox.Audio
    Assembly Version: 0.1.5291.26344
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/Sandbox.Audio.DLL

Sandbox.Input
    Assembly Version: 0.1.5291.26344
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/Sandbox.Input.DLL

SharpDX.DirectInput
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SharpDX.DirectInput.DLL

SharpDX.Direct3D9
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SharpDX.Direct3D9.DLL

SharpDX.XAudio2
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SharpDX.XAudio2.DLL

SharpDX.RawInput
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0
##     CodeBase: file:///D:/DedicatedServer/DedicatedServer64/SharpDX.RawInput.DLL

Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.1022 (RTMGDR.030319-1000)
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by chessmaster42** [comment]
Future note: Please put this details information into a pastebin and link to it from here. That long, bold text is very hard to read.

This issue is fixed in be68b7d29213c7a757de0e86fd329012b7b45f0d

As for the JIT debugging thing we will get to that eventually once we have everything more stable.
