### ISSUE TITLE
Server shutdown/crash on import new enitity.

### ISSUE THREAD

**Issue by StellarwhimsRepo** [SEModCommunity/SE-Community-Mod-API#43]
Exceptions seem to start occuring soon after server instance has loaded. In this session i flew out to a custom asteroid position and built a 2x2 station platform, medbay and small reactor. i then using the seextender 1.8 tool, exported my custom spawnship labeled 'testship'.  All is well so far with a seemingly successful export.  

however, upon creating a new entity to make a copy of this startship using the seextender tool, the server immediately shuts down due to an exception error.  

I have included a link to the full crash log.

https://docs.google.com/document/d/1QS_wyrlkRBopO60ZPng8TKdcCD8rGlxBCiBmeiorCy0/edit?usp=sharing

**Comment by chessmaster42** [comment]
Yeah, sorry about that one. It came up from the last patch but I didn't catch it until last night actually. I have it fixed but don't have a release out for it yet.

Thanks for logging the bug!

P.S. Pastebin is a better place for those logs than google docs, if you don't mind using it.

**Comment by chessmaster42** [comment]
Fixed in 1aceae769e23d7f11233b36b6f7836f930be5b72
