### ISSUE TITLE
Command Line Options

### ISSUE THREAD

**Issue by chessmaster42** [SEModCommunity/SE-Community-Mod-API#47]
Need to add command line options to the startup of the server tool. Suggested options include the following:
-  -path="C:/Path/To/Game/Install" _Overrides any detected game install path with the specified path_
-  -nogui _Turns the server tool GUI off and auto-starts the server_
-  -debug _Turns on debugging_
-  -service _Implies -nogui and starts as a service instead of console app_

There may be more which I'll add to this list as we go.

**Comment by mvolli** [comment]
- custom save path (like you could already do with the servers "-path")

I'd suggest a passthrough of the server command line switches.

**Comment by chessmaster42** [comment]
This is complete as of the latest release. Command line options are as follows:

autostart - Automatically starts the server upon launch
debug - Turns on debugging options
nogui - Hides the GUI and only runs the console
gamepath="C:\PathToGame" - Used to override the detected game path
instance="TestService" - Used to specify a service instance in the ProgramData folder to load from
