### ISSUE TITLE
Show cube grids with unnamed beaons as "Beacon" instead of their entity ID

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#49]
Instead of showing the entity id on a cube grid containing a beacon with no name, could you have it show simply "Beacon"?  That way it is a little easier to see ships that players are working on that may not have named their beacon yet.

**Comment by Hasbinbad** [comment]
A+

**Comment by chessmaster42** [comment]
This has been completed although they sometimes show up as "LargeBlockBeacon" and "SmallBlockBeacon".
