### ISSUE TITLE
v0.2.1 hangs when starting server

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#52]
After pressing start server the load process hangs on "Finished loading ChatManager".

**Comment by chessmaster42** [comment]
Open the normal server config screen and save the config. Then start the world and let it auto-save at least once. This will update your world files to work again. After you have done this try starting it back up with the tool. If it still fails please post your log to pastebin.com and put the link in a comment here.

**Comment by chessmaster42** [comment]
Ignore my previous comment. The source of the problem has been found and will be fixed in the next release.

**Comment by chessmaster42** [comment]
Fixed in 7cb63d46189194647e56a5b71212a9e3c35585b3
