### ISSUE TITLE
Shutdown After Load

### ISSUE THREAD

**Issue by SirOaken** [SEModCommunity/SE-Community-Mod-API#57]
Error log- http://pastebin.com/KbPeNjbd

**Comment by chessmaster42** [comment]
I need more details on this. Please put the version of the tool you were using, where you were running the tool from, and any other information.

**Comment by SirOaken** [comment]
v0.2.3
dedicated server 64 
run on a windows machine

run as admin

**Comment by SirOaken** [comment]
This bug still continues in the latest update. Any idea whats causing it?

**Comment by chessmaster42** [comment]
Fixed in recent pushes but not out in a live build yet.

**Comment by chessmaster42** [comment]
Dev build release is out so this issue is being closed.
