### ISSUE TITLE
Create derivative of ConfigFile interface for AmmoMagazines.sbc

### ISSUE THREAD

**Issue by fvgoulet** [SEModCommunity/SE-Community-Mod-API#6]

**Comment by chessmaster42** [comment]
Taking ownership for wrapper overhaul

**Comment by chessmaster42** [comment]
Relinquishing ownership as overhaul is complete

**Comment by chessmaster42** [comment]
Taking ownership to finish up interface

**Comment by chessmaster42** [comment]
Interface is complete, pending code review

**Comment by Moustachauve** [comment]
Code review complete and Interface is complete
