### ISSUE TITLE
Create derivative of ConfigFile interface for Blueprints.sbc

### ISSUE THREAD

**Issue by fvgoulet** [SEModCommunity/SE-Community-Mod-API#7]

**Comment by Moustachauve** [comment]
I'm working on this interface

I will implement Result Item and Prerequisites items in a class

**Comment by Moustachauve** [comment]
This should now be complete

**Comment by chessmaster42** [comment]
Feature is not quite complete yet. Still missing new and delete functionality

**Comment by chessmaster42** [comment]
This is now complete with all functionality
