### ISSUE TITLE
FloatingObject.LinearVelocity not updating correctly.

### ISSUE THREAD

**Issue by DraygoKorvan** [SEModCommunity/SE-Community-Mod-API#71]
Setting Linearvelocity either does not change the velocity of the floating object or sets it to an X,Y,Z value of less than 1 and greater than -1. 

Editing the velocity value in the SEExtender entity list does not seem to have any effect.

**Comment by chessmaster42** [comment]
Bug verified, still working on fixing.

**Comment by DraygoKorvan** [comment]
Fixed
