### ISSUE TITLE
SEApi/SEServerExtender: Meteor list breaks randomly

### ISSUE THREAD

**Issue by DraygoKorvan** [SEModCommunity/SE-Community-Mod-API#75]
Ok this might be difficult to track down because I don't always seem to get an exception or anything related to it. But after the server runs a while the meteor list ceases to work in it's entirety. 

Currently no duplication steps force it to happen it just happens after the server runs for a while. 

`List<Meteor> entityList = SectorObjectManager.Instance.GetTypedInternalData<Meteor>();` eventually returns nothing when meteors are still spawning and killing stuff in game. The entity list in SEServerExtender also shows nothing after it breaks. 

Best way to get it to break is to set a server on cataclysm for a while.

**Comment by chessmaster42** [comment]
Please test again with latest source build. This was an issue with the old API entity sync code and should no longer be happening.

**Comment by chessmaster42** [comment]
Is this still occurring? If I don't receive a response soon I will assume the issue has been fixed.

**Comment by DraygoKorvan** [comment]
I haven't run into it because I haven't turned my server on cataclysm recently. I don't think ill get to testing this anytime soon, so up to you if you want to close it. I can reopen it if it breaks again.
