### ISSUE TITLE
Nullreference in client when adding FloatingObject

### ISSUE THREAD

**Issue by DraygoKorvan** [SEModCommunity/SE-Community-Mod-API#78]
No errors reported in API and server keeps running

http://pastebin.com/KvKFUajQ

Is the error in the client after addentity is called on a floating object. Client can reconnect to the server successfully, I don't know if its an issue with the API directly or its an issue that keen needs to fix.

**Comment by DraygoKorvan** [comment]
http://pastebin.com/qSYhJs5i is the second one after the latest version.

**Comment by chessmaster42** [comment]
Appears to be related to the floating object changes detailed in the latest patch notes: http://forums.keenswh.com/post/update-01-040-pistons-blast-door-blocks-7006622?trail=15

Not sure yet how to fix but I'm working on it.

**Comment by DraygoKorvan** [comment]
Fixed, by mistake I understand :)
