### ISSUE TITLE
Request: playerid from steamid

### ISSUE THREAD

**Issue by DraygoKorvan** [SEModCommunity/SE-Community-Mod-API#79]
Method to get playerid from steamid. 

I have about 3 separate plugins in the works that need this functionality. 

Thanks for the amazing amount of work so far.

**Comment by chessmaster42** [comment]
The latest release added the SteamId property to CharacterEntity objects. Does this meet the need or do you need to link the actual player id that's used for factions?

**Comment by DraygoKorvan** [comment]
It mostly meets the need

I did run across an instance where for some reason a particular player's character wasn't showing up in the character list at all, even though he was interacting with the world just fine.

**Comment by chessmaster42** [comment]
We will improve the PlayerManager and PlayerMap classes to have an additional convenience function for getting the playerid from steamid and vice versa.

**Comment by chessmaster42** [comment]
Completed in 98d4a9e932d640fab6e0822f023b778861e01e2a

**Comment by DraygoKorvan** [comment]
yea!
