### ISSUE TITLE
BUG: Server shutting down when interacting with objects from the console

### ISSUE THREAD

**Issue by mikeloeven** [SEModCommunity/SE-Community-Mod-API#80]
Deleting \editing block grids or clearing floating objects causes the server to shut down not saving any changes this began after the pistons update

**Comment by chessmaster42** [comment]
Download and use the latest full release of the SEServerExtender tool and see if you are still experiencing this. Floating objects have a number of known issues and most add/delete function for them is currently disabled.

**Comment by chessmaster42** [comment]
Closing this out as there has been no response and all known issues with entity deletion have presently been fixed.
