### ISSUE TITLE
Slower Map Downloads and Connection Interrupts During Autosaves

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#83]
Compared to running the dedicated server as  service, the map download times are about 2x longer using the Server Extender.  Clients are seeing more fluctuations in the download speeds.

Also, during every autosave the clients see a connection interruption during the duration of the save.  So for every autosave which is taking about 5 seconds the client sees a 5 second connection interruption message.  This was also non-existent when running the server as a service.  The autosave caused no interruption.

**Comment by DraygoKorvan** [comment]
Is the autosave configured to be off?

In your config for your world you should have autosave set to off. Extender is taking over the autosave functionality so you do not want the games autosave to trigger.

**Comment by ghost** [comment]
Actually it is on, I'll try turning it off and giving that a try and report back.  Thanks.

**Comment by ghost** [comment]
No change, users still see the connection dropout during saves.  Also on the map downloads when joining the upload speed of the server is getting limited to about 60KB/s and fluctuates down to as low as 5KB/s.

**Comment by ghost** [comment]
For comparison, when running as a service the upload high was 150KB and low was 60KB.

**Comment by chessmaster42** [comment]
Are you running any plugins or is the tool running as-is? Also, can you post your .cfg file (censor any personal details) and the SEModAPIInternal.log files to pastebin.com and put the links here? Do NOT copy paste the content of the files into a comment.

**Comment by ghost** [comment]
At the moment just running the motd plugin but I had the same issues before I was running it as well.

Here my cfg file, I use this same config when running as a standard service: http://pastebin.com/8NTezyRY

SEModAPIInternal: http://pastebin.com/9DG000K7

**Comment by ghost** [comment]
FYI after today's hotfixes and updates the join speed and map down is even slower.

**Comment by DraygoKorvan** [comment]
Can you enable debugging on your server and gather the logs for a while, debugging contains some performance counters that might help shine some light on the issue.

**Comment by chessmaster42** [comment]
Closing as it has been 10 days now since there was any response on this issue and quite a few performance updates have been made in the last few releases.
