### ISSUE TITLE
chat command "/delete ship" "name=" and wildcard support

### ISSUE THREAD

**Issue by Hasbinbad** [SEModCommunity/SE-Community-Mod-API#89]
please add the feature to where you can use name="x" strings with wildcards, such that:

/delete ship name="Supercali*"

would delete all ships which matched the string, such as "Supercalifragilisticexpealidocious" and "SuperCaliCoolguy"

Thanks!

**Comment by ghost** [comment]
yes I'd like to see the delete command work via entity name as well!
