### ISSUE TITLE
Create derivative of ConfigFile interface for ContainerType.sbc

### ISSUE THREAD

**Issue by fvgoulet** [SEModCommunity/SE-Community-Mod-API#9]

**Comment by chessmaster42** [comment]
I'm starting on this one and the corresponding tab in the config tool tonight.

**Comment by chessmaster42** [comment]
Completed in b72b4498a3cff98e2ff7d9d7bbd45763b05e3a30

**Comment by chessmaster42** [comment]
Re-opening as I realized that I don't have the interfaces to the sub-objects completed.

**Comment by chessmaster42** [comment]
Working on minor overhaul of manager class to be more flexible with sub-items in interfaces like this one. Also working on finalizing this interface.

**Comment by chessmaster42** [comment]
Still needs delete functionality in config tool but rest is complete

**Comment by chessmaster42** [comment]
Completed in API and config tool
