### ISSUE TITLE
SEServerExtender Does Not Honor gamepath like SpaceEngineersDedicated.exe -path

### ISSUE THREAD

**Issue by joseraffucci** [SEModCommunity/SE-Community-Mod-API#93]
While playing with SEServerExtender I found a discrepancy when attempting to load a configuration in the current working directory.  

I am running out of the DedicatedServer64 directory.  When I launch the server directly with "SpaceEngineersDedicated.exe -noconsole -path ." from the command line It creates a Saves and Mods directory in the DedicatedServer64 directory. It also loads the configuration file from this directory and It also generates the world in the Saves directory.  

I can not seem to get SEServerExtender to behave similarly.  I attempted to modify GetUserDataPath in the SandboxGameAssemblyWrappers.cs  This worked to load the configuration file but when the server started it still tried to create the data in the %appdata%\SpaceEngineersDedicated directory. 

Nothing I tried could get the server to look in the current working directory for the Saves folder.  I believe it has to do with the DedicatedServerStartupBaseMethod and the methodParams but I am not familiar with the code base to go any further.  If someone could point me in the right direction on how to get it to behave the same way I would be glad to do the work and submit a pull request.  

Thank you in advance.

**Comment by chessmaster42** [comment]
What you're experiencing isn't a bug. You need to also be setting the "instance" command line arg. It's a relative path to ProgramData/SpaceEngineersDedicated

So if your world is in C:\SpaceEngineers\MyWorld then the path you need to give for instance will be like this:

"../../SpaceEngineers/MyWorld"

The reason this is a relative path is that most servers use the default ProgramData folder for the server instances but you can get around it using the above method.

**Comment by joseraffucci** [comment]
Hi Chessmaster42, 

Thank you very much.  I will test and update you again shortly.  

Where is the tip jar :+1:

**Comment by chessmaster42** [comment]
Just finished adding a path override that should work just like the vanilla option. It will be in the next dev build.
