### ISSUE TITLE
BUG: Items in storage containers do not show item name.

### ISSUE THREAD

**Issue by NeoSword** [SEModCommunity/SE-Community-Mod-API#94]
Running 0.2.5.7Dev
With Drego mods SE-utils and Meteor

Seeing 2 issues but cannot locate any log related data for one.
#1

This has been constant for several builds.
Items in storage containers do not show names, but i can still edit amount.
This may be due to running from custom directory?

SteamCmd
c:\ST
SpaceEngineers full install
C:\SE
Running save files from
C:\ProgramData\SpaceEngineersDedicated\INSTANCE

Logs:
http://pastebin.com/YS8uCrrB
#2

Several reports of players loosing ownership after log off, Items are still there and related user player ID marked as 'isdead' = true.

No logs for this yet. enabling debug tonight to see if i can locate.
Will file separate bug when i have more info.

**Comment by DraygoKorvan** [comment]
#2 is a keen issue as I understand.

**Comment by chessmaster42** [comment]
Can you include a screenshot for this? I haven't experienced this and can't reproduce the problem on my end. This is also the first I've heard about it so more details is better.

As for that second problem, that's a totally separate bug in the game itself that isn't related to the main issue.

**Comment by NeoSword** [comment]
I have since moved to build 0.2.8.2 where I am forced to launch with Gamedata="c:\se" (I did not use this previously) to get server to load. I no longer have this issue on this build. I can consider my bug closed and will reopen should this behavior change.
