### ISSUE TITLE
Gamepath & instance path - crashes tool with \ on end

### ISSUE THREAD

**Issue by Ragonz2** [SEModCommunity/SE-Community-Mod-API#95]
When starting the tool in nogui noconsole mode if you put in the gamepath and instance path with a \ on the end example

Gamepath="C:\Dir\Dir\123\" Instance="C:\Dir\Dir\123\"

It crashes the tool, removing the trailing \ allows it to work fine

**Comment by chessmaster42** [comment]
First, instance is a relative path and won't work as expected if you define it as an absolute path. You need to precede it with "../../" to move the relative path up out of the default ProgramData/SpaceEngineersDedicated/ path.

Second does it crash if either of those have a trailing slash or only if a certain one does? We have made some fixes to the way gamepath is detected and used so please try on the latest dev build and let me know if it is any better.

**Comment by chessmaster42** [comment]
Is there any update on this? Does this still happen with the latest production release? Please supply more details and re-test on the latest build.

**Comment by Ragonz2** [comment]
Confirmed resolved
