### ISSUE TITLE
OnPlayerJoined System.NullReferenceException

### ISSUE THREAD

**Issue by RayFinney** [SEModCommunity/SE-Community-Mod-API#98]
When i try to use:
public void OnPlayerJoined(ulong remoteUserId, CharacterEntity character)

I will get a System.NullReferenceException but its should be right this way isnt it?

**Comment by DraygoKorvan** [comment]
character is currently a dummy and only has the steamId, so if you try to access other properties the mod can error out with a nullreference. When writing your OnPlayerJoined only use the remoteUserId that it gets for now. 

The dev branch changes the OnPlayerJoined to only pass the steamId, removing the CharacterEntity entirely.

**Comment by chessmaster42** [comment]
This is completed now that the event no longer passes the entity. The player events only pass the steam id now.
