### ISSUE TITLE
0.2.8.2-dev - Cannot start server

### ISSUE THREAD

**Issue by spamenigma** [SEModCommunity/SE-Community-Mod-API#99]
Hi
Clean install of SE dedicated server files, clean copy of 0.2.8.2-dev files into Space Engineers\DedicatedServer64.

Ensured to set to run as administrator.

SEServerExtender starts with the console. but clicking start server for either of my server instances does nothing. The console's last entries are Finished loading PlayerManager and Finished loading NetworkManager when I click start server, then nothing more happens.

Thanks

**Comment by DraygoKorvan** [comment]
You need to specify the gamepath, add the gamepath argument that points to the folder with Content, DedicatedServer, and DedicatedServer64 directories. 

Chess knows about this issue, but the above should allow you to launch your game.

**Comment by NeoSword** [comment]
As this may be helpful others. It took me a minute to piece together.
My space engineers install dir is c:\se So I used:
C:\se\DedicatedServer64\SEServerExtender.exe gamepath="C:\se" instance="INSTANCENAME" autostart

**Comment by chessmaster42** [comment]
There have been a number of improvements around this that this question is no longer valid. If you continue to have an issue feel free to re-open the issue.
